name: Build Recovery (VendorBoot)

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'AOSP manifest URL (SSH or HTTPS)'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp'
      MANIFEST_BRANCH:
        description: 'Manifest branch (e.g., twrp-12.1)'
        required: true
        default: 'twrp-12.1'
      DEVICE_TREE_URL:
        description: 'Git URL for device tree (SSH or HTTPS)'
        required: true
        default: 'https://github.com/MayuriLabs/recovery_device_xiaomi_moon'
      DEVICE_TREE_BRANCH:
        description: 'Device tree branch'
        required: true
        default: 'main'
      DEVICE_PATH:
        description: 'Path to device tree in workspace'
        required: true
        default: 'device/xiaomi/moon'
      MAKE_TARGET:
        description: 'Make target for lunch (e.g., twrp_moon-eng)'
        required: true
        default: 'twrp_moon-eng'
      BUILD_TARGET:
        description: 'Build target (e.g., vendorbootimage)'
        required: true
        default: 'vendorbootimage'

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y \
          bc bison build-essential ccache curl flex \
          git gnupg gperf imagemagick lib32ncurses-dev \
          liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev \
          libxml2-utils lzop openjdk-11-jdk pngcrush rsync schedtool \
          squashfs-tools xsltproc zip zlib1g-dev repo

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Configure Git SSH (if needed)
      if: |
        startsWith(github.event.inputs.MANIFEST_URL, 'git@') ||
        startsWith(github.event.inputs.DEVICE_TREE_URL, 'git@')
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install repo tool
      run: |
        mkdir -p ~/bin
        curl -sS https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo mv ~/bin/repo /usr/local/bin/

    - name: Initialize AOSP repo
      id: init
      run: |
        mkdir workspace && cd workspace
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
        echo "WORKDIR=$(pwd)" >> $GITHUB_OUTPUT

    - name: Sync AOSP tree
      run: repo sync -c -j$(nproc) --force-sync
      working-directory: ${{ steps.init.outputs.WORKDIR }}

    - name: Clone device tree
      run: |
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} \
          ${{ steps.init.outputs.WORKDIR }}/${{ github.event.inputs.DEVICE_PATH }}

    - name: Setup environment
      run: |
        cd ${{ steps.init.outputs.WORKDIR }}
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true

    - name: Build VendorBoot Image
      run: |
        cd ${{ steps.init.outputs.WORKDIR }}
        lunch ${{ github.event.inputs.MAKE_TARGET }}
        mka ${{ github.event.inputs.BUILD_TARGET }} -j$(nproc)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.BUILD_TARGET }}
        path: workspace/out/target/product/moon/${{ github.event.inputs.BUILD_TARGET }}.img
